### ISSUE TITLE
UIoskirjautumisessa Firefoxilla ongelma

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#10]
Uloskirjautumisessa on Firefoxilla sellainen ongelma, että käyttäjän klikattua "Kirjaudu ulos" linkkiä, tätä ei uudelleenohjata oikein kirjautumissivulle vaan käyttäjä päätyy ylläpitotyökalun etusivulle. Kun selaimen sulkee ja avaa uudestaan on session kuitenkin päättynyt.

**Comment by jaakkos** [comment]
Näyttää olevan todella mystinen. Tekee redirect:n mutta ilmeisesti DELETE request:i ei lähde.

**Comment by jaakkos** [comment]
Korjattu versio staging:ssä

https://github.com/tkrekry/tkrekry-admin/commit/80e9552a565ac55f7d06138f038c028021a72d96
