### ISSUE TITLE
Organisaatiohallinta -> Terveyskeskuksen muokkauksessa virheitä

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#12]
Jos yrittää muokata sellaista terveyskeskusta, jolle ei ole määritetty ERVA-aluetta ja/tai sairaanhoitopiiriä, tulee seuraava virhe.
![1-organisaatiohallinta-tk-muokkaus](https://cloud.githubusercontent.com/assets/189542/9567863/31f24d98-4f42-11e5-8d3e-82769d986fed.PNG)

**Comment by bircha** [comment]
Sama Firefoxilla. 
![1-organisaatiohallinta-tk-muokkaus-2](https://cloud.githubusercontent.com/assets/189542/9567979/e872e246-4f45-11e5-8406-c65c1c36d308.PNG)

Tuotannossa ko. näkymässä muutosten tallentaminen heittää virheen ($scope.employer.district is undefined) joka ei toistu env-upgrade haarassa lokaalilla ympäristöllä. Käyttöliittymä kuitenkin näyttää, että TK:n sairaanhoitopiiri on määritetty.

**Comment by jaakkos** [comment]
Ei pitäisi olla terveyskeskusta ilman ervaa tai sairaanhoitopiiriä
