### ISSUE TITLE
Terveyskeskuksen tiedot näkymä ei aukea

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#13]
Terveyskeskuksen tiedot näkymä ei aukea (sen sijaan käyttäjä ohjataan työpaikkailmoituslistaukseen), jos pääkäyttäjää ei ole kiinnitetty yhteenkään terveyskeskukseen. Toimii siis eri tavoin kuin mitä nyt tuotannossa.

**Comment by jaakkos** [comment]
Ongelma on siinä ettei voi olla admin käyttäjää joka ei ole kiinnitetty yhteenkään. Ei mahdollista ratkaista UI:ssa vaan pitää hakea syy miksi on syntynyt admin käyttäjä ilman terveyskeskusta.

**Comment by bircha** [comment]
Tosiaan tuotannossa pääkäyttäjiä ei ole kiinnitetty (käyttöliittymästä päätellen) terveyskeskuksiin. Päivityksen myötä nämä täytyy sitten käydä kliksuttelemassa läpi?
