### ISSUE TITLE
Kirjautumisen jälkeisellä etusivulla "Päivitä tiedot" -linkki ei toimi

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#14]
Kun kirjautuu TK-käyttäjänä sisään, niin kirjautumisen jälkeisellä etusivulla "Päivitä tiedot" -linkki ei toimi.

**Comment by jaakkos** [comment]
tuleeko virhettä?

On 31 August 2015 at 17:57, Pirkka Rannikko <notifications@github.com>
wrote:

> Assigned #14 <https://github.com/tkrekry/tkrekry-admin/issues/14> to
> @jaakkos <https://github.com/jaakkos>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkrekry/tkrekry-admin/issues/14#event-396753006>.
>



-- 
--
- Jaakko Suutarla
- jaakko(a)suutarla.com

**Comment by bircha** [comment]
Ei, linkki vaan ei toimi, koska ilmeisesti URL osoittaa väärään paikkaan tms.
