### ISSUE TITLE
Julkaistun ilmoituksen haun päättymisen aika eroaa tallennetusta

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#18]
Ks. kuvat.

Julkaistu haun päättymisen kellon aika klo 12, Adminiin tallennettu aika klo 15.

![1](https://cloud.githubusercontent.com/assets/189542/14143257/03f081be-f693-11e5-96b6-c845e3405968.PNG)
![2](https://cloud.githubusercontent.com/assets/189542/14143256/03ed9a44-f693-11e5-8a08-f2237fe012e6.PNG)
![3](https://cloud.githubusercontent.com/assets/189542/14143255/03ec0ee0-f693-11e5-9aff-a859f014b35f.PNG)

**Comment by jaakkos** [comment]
Näyttää timezone issuelta koska on juuri kolme tuntia.

**Comment by jaakkos** [comment]
Ei liity admin käyttöliittymään vaan siihen että että sivustolla ilmoitukset näytettiin UTC ajassa, nyt kaikki aika määreet käsitellään Helsingin aikavyöhykkeellä https://github.com/tkrekry/tkrkery-site-v2/commit/31bc7f2fda04ac56e929de76e5e9fd2928d51367
