### ISSUE TITLE
Kun tekee uuden työpaikkailmoituksen ja painaa “Julkaise” ennen kuin painaa “Tallenna”, niin mitään ei tapahdu

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#2]
Kun tekee uuden työpaikkailmoituksen ja painaa “Julkaise” ennen kuin painaa “Tallenna”, niin mitään ei tapahdu (ei tule dialogia tms.). Jos käyttäjä tämän jälkeen poistuu näkymästä, niin tiedot menetetään. 
-> Disabloidaan “Julkaise”, kunnes ilmoitus on tallennettu.

**Comment by bircha** [comment]
"Julkaise" -painikkeen disablointi toimii. Suljetaan.

**Comment by bircha** [comment]
Sitten pitää vielä miettiä mitä tehdään, kun muokkaa olemassa olevaa ilmoitusta ja painaa "Julkaise" tallentamatta...

**Comment by jaakkos** [comment]
Tehdään siitä oma taski koska se ei liity tähän.
