### ISSUE TITLE
Virhe 12 merkkisen salansanan tallennuksessa

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#36]
Kun syöttää 12 merkkisen salasanan, jossa on numeroita ja isoja sekä pieniä kirjaimia esim. Pilipali2019 niin kentän fronttivalidaatio menee läpi, mutta lomakkeen tallentaminen palauttaa virheen joka sanoo "Nykyinen salasana on pakollinen kenttä." vaikka nykyisen salasanan on syöttänyt.

13 merkkiä pitkä salasana tallentuu ongelmitta esim. Pilipali20199.

**Comment by jaakkos** [comment]
Korjattu https://github.com/tkrekry/tkrekry-admin/commit/0c4950935e89d3afec06f36f4b4bcf21218569ff
