### ISSUE TITLE
Omat tiedot, tietoja on päivitetty viimeksi päiväystä ei rendata jostain syystä.

### ISSUE THREAD

**Issue by bircha** [tkrekry/tkrekry-admin#5]
Ks. https://github.com/tkrekry/tkrekry-admin/blob/master/app/views/settings/edit.html#L20 -> Poista aaltosulkeet päiväyksen ympäriltä.

**Comment by jaakkos** [comment]
Korjattu version asennettu stagingiin.

**Comment by jaakkos** [comment]
https://github.com/tkrekry/tkrekry-admin/commit/1ec8dbb504f1725db33a6bd7f526c16e556852a9
